version: '2'
services:
  harbor-audit:
    build: .
    image: registry.services.dmtio.net/harbor-audit:0.0.4
    ports:
      - "80:5000"
    environment:
      PORT: 5000
      HEALTHCHECK: /health
      SHIPIT_API: http://shipit.services.dmtio.net/